version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=project1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=letmein
      - MYSQL_ROOT_PASSWORD=letmein
      - SERVICE_TAGS=dev
      - MYSQL_NAME=mysqldb
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./database/config/config:docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
  app:
    image: node:16
    depends_on:
      - mysqldb
    build: ./bezkoder-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=3000
    stdin_open: true
    tty: true

volumes: 
  db: